apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "{{ .Values.service.targetPort }}"
