---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analyzers
  namespace: mcp-devops-automation
  labels:
    app.kubernetes.io/name: analyzers
    app.kubernetes.io/part-of: mcp-devops-automation
spec:
  selector:
    matchLabels:
      app: analyzers
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: calculators
  namespace: mcp-devops-automation
  labels:
    app.kubernetes.io/name: calculators
    app.kubernetes.io/part-of: mcp-devops-automation
spec:
  selector:
    matchLabels:
      app: calculators
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: generators
  namespace: mcp-devops-automation
  labels:
    app.kubernetes.io/name: generators
    app.kubernetes.io/part-of: mcp-devops-automation
spec:
  selector:
    matchLabels:
      app: generators
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tools
  namespace: mcp-devops-automation
  labels:
    app.kubernetes.io/name: tools
    app.kubernetes.io/part-of: mcp-devops-automation
spec:
  selector:
    matchLabels:
      app: tools
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: types
  namespace: mcp-devops-automation
  labels:
    app.kubernetes.io/name: types
    app.kubernetes.io/part-of: mcp-devops-automation
spec:
  selector:
    matchLabels:
      app: types
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
---

# Pod Monitor for services without Service
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mcp-devops-automation-pods
  namespace: mcp-devops-automation
  labels:
    app.kubernetes.io/part-of: mcp-devops-automation
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: mcp-devops-automation
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
