# Secure Service Accounts with IRSA (IAM Roles for Service Accounts)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analyzers
  namespace: mcp-devops-automation
  annotations:
    # AWS IAM role for this service
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/mcp-devops-automation-analyzers
automountServiceAccountToken: false  # Don't auto-mount tokens

---
# Token request for analyzers
apiVersion: v1
kind: Secret
metadata:
  name: analyzers-token
  namespace: mcp-devops-automation
  annotations:
    kubernetes.io/service-account.name: analyzers
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calculators
  namespace: mcp-devops-automation
  annotations:
    # AWS IAM role for this service
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/mcp-devops-automation-calculators
automountServiceAccountToken: false  # Don't auto-mount tokens

---
# Token request for calculators
apiVersion: v1
kind: Secret
metadata:
  name: calculators-token
  namespace: mcp-devops-automation
  annotations:
    kubernetes.io/service-account.name: calculators
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: generators
  namespace: mcp-devops-automation
  annotations:
    # AWS IAM role for this service
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/mcp-devops-automation-generators
automountServiceAccountToken: false  # Don't auto-mount tokens

---
# Token request for generators
apiVersion: v1
kind: Secret
metadata:
  name: generators-token
  namespace: mcp-devops-automation
  annotations:
    kubernetes.io/service-account.name: generators
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tools
  namespace: mcp-devops-automation
  annotations:
    # AWS IAM role for this service
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/mcp-devops-automation-tools
automountServiceAccountToken: false  # Don't auto-mount tokens

---
# Token request for tools
apiVersion: v1
kind: Secret
metadata:
  name: tools-token
  namespace: mcp-devops-automation
  annotations:
    kubernetes.io/service-account.name: tools
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: types
  namespace: mcp-devops-automation
  annotations:
    # AWS IAM role for this service
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/mcp-devops-automation-types
automountServiceAccountToken: false  # Don't auto-mount tokens

---
# Token request for types
apiVersion: v1
kind: Secret
metadata:
  name: types-token
  namespace: mcp-devops-automation
  annotations:
    kubernetes.io/service-account.name: types
type: kubernetes.io/service-account-token

