{{- if .Values.certManager.createClusterIssuer -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuerName | default "letsencrypt-prod" }}
spec:
  acme:
    server: {{ .Values.certManager.server | default "https://acme-v02.api.letsencrypt.org/directory" }}
    email: {{ .Values.certManager.email | required "certManager.email is required" }}
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretName | default (printf "%s-key" (include "ui.fullname" .)) }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className | default "nginx" }}
{{- end }}
