# GitLeaks configuration for secret detection
[allowlist]
  description = "Allowlisted files and patterns"
  files = [
    '''go.sum''',
    '''package-lock.json''',
    '''yarn.lock'''
  ]

[[rules]]
  description = "AWS Access Key"
  regex = '''(?i)aws(.{0,20})?['"][0-9a-zA-Z]{16,20}['"]'''
  tags = ["aws", "key"]

[[rules]]
  description = "AWS Secret Key"
  regex = '''(?i)aws(.{0,20})?['"][0-9a-zA-Z/+=]{40}['"]'''
  tags = ["aws", "secret"]

[[rules]]
  description = "Generic API Key"
  regex = '''(?i)api[_-]?key['"]?\s*[:=]\s*['"][0-9a-zA-Z]{32,45}['"]'''
  tags = ["api", "key"]

[[rules]]
  description = "Private Key"
  regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----'''
  tags = ["private", "key"]
