# HashiCorp Vault setup for secret management
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault
  namespace: vault
spec:
  chart: vault
  repo: https://helm.releases.hashicorp.com
  targetNamespace: vault
  valuesContent: |-
    server:
      ha:
        enabled: true
        replicas: 3

      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: gp3

      ingress:
        enabled: true
        hosts:
          - host: vault.mcp-devops-automation.example.com

      # Auto-unseal with AWS KMS
      extraEnvironmentVars:
        VAULT_SEAL_TYPE: awskms
        VAULT_AWSKMS_SEAL_KEY_ID: ${AWS_KMS_KEY_ID}

    ui:
      enabled: true

    # Inject secrets into pods
    injector:
      enabled: true
      agentImage:
        repository: "hashicorp/vault"
        tag: "latest"
